config/routes.rb
Rails.application.routes.draw do
  root 'sales#index'
  devise_for :users
  resources :sales
  resources :products
  resources :orders
  resources :monthly_sales
  resources :daily_sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daily_sale.rb
class DailySale < ApplicationRecord
end

app/controllers/daily_sales_controller.rb
class DailySalesController < ApplicationController
  before_action :set_daily_sale, only: [:show, :edit, :update, :destroy]

  # GET /daily_sales
  # GET /daily_sales.json
  def index
    @daily_sales = DailySale.all
  end

  # GET /daily_sales/1
  # GET /daily_sales/1.json
  def show
  end

  # GET /daily_sales/new
  def new
    @daily_sale = DailySale.new
  end

  # GET /daily_sales/1/edit
  def edit
  end

  # POST /daily_sales
  # POST /daily_sales.json
  def create
    @daily_sale = DailySale.new(daily_sale_params)

    respond_to do |format|
      if @daily_sale.save
        format.html { redirect_to @daily_sale, notice: 'Daily sale was successfully created.' }
        format.json { render :show, status: :created, location: @daily_sale }
      else
        format.html { render :new }
        format.json { render json: @daily_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_sales/1
  # PATCH/PUT /daily_sales/1.json
  def update
    respond_to do |format|
      if @daily_sale.update(daily_sale_params)
        format.html { redirect_to @daily_sale, notice: 'Daily sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_sale }
      else
        format.html { render :edit }
        format.json { render json: @daily_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_sales/1
  # DELETE /daily_sales/1.json
  def destroy
    @daily_sale.destroy
    respond_to do |format|
      format.html { redirect_to daily_sales_url, notice: 'Daily sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_sale
      @daily_sale = DailySale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_sale_params
      params.require(:daily_sale).permit(:product_name, :customer_name, :pri_quantity, :sec_quantity, :pri_rate, :sec_rate, :total)
    end
end

app/helpers/daily_sales_helper.rb
module DailySalesHelper
end

app/views/daily_sales/_form.html.erb
<%= form_with(model: daily_sale, local: true) do |form| %>
  <% if daily_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_sale.errors.count, "error") %> prohibited this daily_sale from being saved:</h2>

      <ul>
      <% daily_sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :daily_sale_product_name %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name, id: :daily_sale_customer_name %>
  </div>

  <div class="field">
    <%= form.label :pri_quantity %>
    <%= form.number_field :pri_quantity, id: :daily_sale_pri_quantity %>
  </div>

  <div class="field">
    <%= form.label :sec_quantity %>
    <%= form.number_field :sec_quantity, id: :daily_sale_sec_quantity %>
  </div>

  <div class="field">
    <%= form.label :pri_rate %>
    <%= form.number_field :pri_rate, id: :daily_sale_pri_rate %>
  </div>

  <div class="field">
    <%= form.label :sec_rate %>
    <%= form.number_field :sec_rate, id: :daily_sale_sec_rate %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total, id: :daily_sale_total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_sales/edit.html.erb
<h1>Editing Daily Sale</h1>

<%= render 'form', daily_sale: @daily_sale %>

<%= link_to 'Show', @daily_sale %> |
<%= link_to 'Back', daily_sales_path %>

app/views/daily_sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Sales</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Customer name</th>
      <th>Pri quantity</th>
      <th>Sec quantity</th>
      <th>Pri rate</th>
      <th>Sec rate</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_sales.each do |daily_sale| %>
      <tr>
        <td><%= daily_sale.product_name %></td>
        <td><%= daily_sale.customer_name %></td>
        <td><%= daily_sale.pri_quantity %></td>
        <td><%= daily_sale.sec_quantity %></td>
        <td><%= daily_sale.pri_rate %></td>
        <td><%= daily_sale.sec_rate %></td>
        <td><%= daily_sale.total %></td>
        <td><%= link_to 'Show', daily_sale %></td>
        <td><%= link_to 'Edit', edit_daily_sale_path(daily_sale) %></td>
        <td><%= link_to 'Destroy', daily_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Sale', new_daily_sale_path %>

app/views/daily_sales/new.html.erb
<h1>New Daily Sale</h1>

<%= render 'form', daily_sale: @daily_sale %>

<%= link_to 'Back', daily_sales_path %>

app/views/daily_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @daily_sale.product_name %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @daily_sale.customer_name %>
</p>

<p>
  <strong>Pri quantity:</strong>
  <%= @daily_sale.pri_quantity %>
</p>

<p>
  <strong>Sec quantity:</strong>
  <%= @daily_sale.sec_quantity %>
</p>

<p>
  <strong>Pri rate:</strong>
  <%= @daily_sale.pri_rate %>
</p>

<p>
  <strong>Sec rate:</strong>
  <%= @daily_sale.sec_rate %>
</p>

<p>
  <strong>Total:</strong>
  <%= @daily_sale.total %>
</p>

<%= link_to 'Edit', edit_daily_sale_path(@daily_sale) %> |
<%= link_to 'Back', daily_sales_path %>