config/routes.rb
Rails.application.routes.draw do
  root 'sales#index'
  devise_for :users
  resources :sales
  resources :products
  resources :orders
  resources :monthly_sales
  resources :daily_sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/monthly_sale.rb
class MonthlySale < ApplicationRecord
end

app/controllers/monthly_sales_controller.rb
class MonthlySalesController < ApplicationController
  before_action :set_monthly_sale, only: [:show, :edit, :update, :destroy]

  # GET /monthly_sales
  # GET /monthly_sales.json
  def index
    @monthly_sales = MonthlySale.all
  end

  # GET /monthly_sales/1
  # GET /monthly_sales/1.json
  def show
  end

  # GET /monthly_sales/new
  def new
    @monthly_sale = MonthlySale.new
  end

  # GET /monthly_sales/1/edit
  def edit
  end

  # POST /monthly_sales
  # POST /monthly_sales.json
  def create
    @monthly_sale = MonthlySale.new(monthly_sale_params)

    respond_to do |format|
      if @monthly_sale.save
        format.html { redirect_to @monthly_sale, notice: 'Monthly sale was successfully created.' }
        format.json { render :show, status: :created, location: @monthly_sale }
      else
        format.html { render :new }
        format.json { render json: @monthly_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_sales/1
  # PATCH/PUT /monthly_sales/1.json
  def update
    respond_to do |format|
      if @monthly_sale.update(monthly_sale_params)
        format.html { redirect_to @monthly_sale, notice: 'Monthly sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @monthly_sale }
      else
        format.html { render :edit }
        format.json { render json: @monthly_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_sales/1
  # DELETE /monthly_sales/1.json
  def destroy
    @monthly_sale.destroy
    respond_to do |format|
      format.html { redirect_to monthly_sales_url, notice: 'Monthly sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_sale
      @monthly_sale = MonthlySale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monthly_sale_params
      params.require(:monthly_sale).permit(:product_name, :customer_name, :pri_quantity, :sec_quantity, :pri_rate, :sec_rate, :total)
    end
end

app/helpers/monthly_sales_helper.rb
module MonthlySalesHelper
end

app/views/monthly_sales/_form.html.erb
<%= form_with(model: monthly_sale, local: true) do |form| %>
  <% if monthly_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monthly_sale.errors.count, "error") %> prohibited this monthly_sale from being saved:</h2>

      <ul>
      <% monthly_sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :monthly_sale_product_name %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name, id: :monthly_sale_customer_name %>
  </div>

  <div class="field">
    <%= form.label :pri_quantity %>
    <%= form.number_field :pri_quantity, id: :monthly_sale_pri_quantity %>
  </div>

  <div class="field">
    <%= form.label :sec_quantity %>
    <%= form.number_field :sec_quantity, id: :monthly_sale_sec_quantity %>
  </div>

  <div class="field">
    <%= form.label :pri_rate %>
    <%= form.number_field :pri_rate, id: :monthly_sale_pri_rate %>
  </div>

  <div class="field">
    <%= form.label :sec_rate %>
    <%= form.number_field :sec_rate, id: :monthly_sale_sec_rate %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total, id: :monthly_sale_total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monthly_sales/edit.html.erb
<h1>Editing Monthly Sale</h1>

<%= render 'form', monthly_sale: @monthly_sale %>

<%= link_to 'Show', @monthly_sale %> |
<%= link_to 'Back', monthly_sales_path %>

app/views/monthly_sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monthly Sales</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Customer name</th>
      <th>Pri quantity</th>
      <th>Sec quantity</th>
      <th>Pri rate</th>
      <th>Sec rate</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monthly_sales.each do |monthly_sale| %>
      <tr>
        <td><%= monthly_sale.product_name %></td>
        <td><%= monthly_sale.customer_name %></td>
        <td><%= monthly_sale.pri_quantity %></td>
        <td><%= monthly_sale.sec_quantity %></td>
        <td><%= monthly_sale.pri_rate %></td>
        <td><%= monthly_sale.sec_rate %></td>
        <td><%= monthly_sale.total %></td>
        <td><%= link_to 'Show', monthly_sale %></td>
        <td><%= link_to 'Edit', edit_monthly_sale_path(monthly_sale) %></td>
        <td><%= link_to 'Destroy', monthly_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monthly Sale', new_monthly_sale_path %>

app/views/monthly_sales/new.html.erb
<h1>New Monthly Sale</h1>

<%= render 'form', monthly_sale: @monthly_sale %>

<%= link_to 'Back', monthly_sales_path %>

app/views/monthly_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @monthly_sale.product_name %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @monthly_sale.customer_name %>
</p>

<p>
  <strong>Pri quantity:</strong>
  <%= @monthly_sale.pri_quantity %>
</p>

<p>
  <strong>Sec quantity:</strong>
  <%= @monthly_sale.sec_quantity %>
</p>

<p>
  <strong>Pri rate:</strong>
  <%= @monthly_sale.pri_rate %>
</p>

<p>
  <strong>Sec rate:</strong>
  <%= @monthly_sale.sec_rate %>
</p>

<p>
  <strong>Total:</strong>
  <%= @monthly_sale.total %>
</p>

<%= link_to 'Edit', edit_monthly_sale_path(@monthly_sale) %> |
<%= link_to 'Back', monthly_sales_path %>