config/routes.rb
Rails.application.routes.draw do
  root 'sales#index'
  devise_for :users
  resources :sales
  resources :products
  resources :orders
  resources :monthly_sales
  resources :daily_sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:product_name, :customer_name, :pri_quantity, :sec_quantity, :pri_rate, :sec_rate, :total)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.collection_select :product_name, Product.all,:id,:product_name, include_blank: true %>  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name, id: :sale_customer_name %>
  </div>

  <div class="field">
    <%= form.label :pri_quantity %>
    <%= form.number_field :pri_quantity, id: :sale_pri_quantity %>
  </div>

  <div class="field">
    <%= form.label :sec_quantity %>
    <%= form.number_field :sec_quantity, id: :sale_sec_quantity %>
  </div>

  <div class="field">
    <%= form.label :pri_rate %>
    <%= form.number_field :pri_rate, id: :sale_pri_rate %>
  </div>

  <div class="field">
    <%= form.label :sec_rate %>
    <%= form.number_field :sec_rate, id: :sale_sec_rate %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total, id: :sale_total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Customer name</th>
      <th>Pri quantity</th>
      <th>Sec quantity</th>
      <th>Pri rate</th>
      <th>Sec rate</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.product_name %></td>
        <td><%= sale.customer_name %></td>
        <td><%= sale.pri_quantity %></td>
        <td><%= sale.sec_quantity %></td>
        <td><%= sale.pri_rate %></td>
        <td><%= sale.sec_rate %></td>
        <td><%= sale.total %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @sale.product_name %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @sale.customer_name %>
</p>

<p>
  <strong>Pri quantity:</strong>
  <%= @sale.pri_quantity %>
</p>

<p>
  <strong>Sec quantity:</strong>
  <%= @sale.sec_quantity %>
</p>

<p>
  <strong>Pri rate:</strong>
  <%= @sale.pri_rate %>
</p>

<p>
  <strong>Sec rate:</strong>
  <%= @sale.sec_rate %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>